/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#645591",
        "primary": "#15023f",
        "on-primary-fixed-variant": "#4c3d77",
        "inverse-on-surface": "#f9efe1",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#6e3900",
        "ink-dark": "#1F1440",
        "teal-accent": "#14B8A6",
        "on-primary": "#ffffff",
        "primary-fixed": "#e8ddff",
        "surface-container-low": "#fcf2e3",
        "on-tertiary": "#ffffff",
        "indigo-dark": "#241454",
        "outline": "#797580",
        "primary-container": "#2a1b54",
        "ink-muted": "#4C3B7C",
        "surface": "#FDF3E4",
        "coral-accent": "#F2994A",
        "on-secondary-container": "#534283",
        "on-surface": "#1f1b12",
        "on-primary-container": "#9384c3",
        "secondary-fixed-dim": "#cfbdff",
        "pink-accent": "#E6396B",
        "on-tertiary-fixed": "#2f1500",
        "on-surface-variant": "#48454f",
        "surface-container-highest": "#ebe1d3",
        "background": "#fff8f1",
        "surface-bright": "#fff8f1",
        "on-background": "#1f1b12",
        "surface-container-high": "#f1e7d8",
        "tertiary-container": "#3d1d00",
        "on-secondary": "#ffffff",
        "surface-dim": "#e2d9ca",
        "secondary-container": "#c7b3fe",
        "on-primary-fixed": "#1f0f49",
        "surface-variant": "#ebe1d3",
        "surface-card": "#FFFFFF",
        "cream": "#FDF3E4",
        "primary-fixed-dim": "#cebdff",
        "sky-accent": "#3B5BFF",
        "on-tertiary-container": "#cb792c",
        "on-secondary-fixed-variant": "#4d3c7d",
        "on-secondary-fixed": "#200c4f",
        "secondary-fixed": "#e8ddff",
        "on-error": "#ffffff",
        "surface-container": "#f6edde",
        "inverse-surface": "#353026",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb77d",
        "tertiary": "#1f0c00",
        "inverse-primary": "#cebdff",
        "secondary": "#655496",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#cac4d0",
        "tertiary-fixed": "#ffdcc3",
        "ink": "#2A1B54",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      fontFamily: {
        "title-lg": ["Epilogue", "sans-serif"],
        "headline-lg-mobile": ["Epilogue", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "display": ["Epilogue", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headings": ["Poppins", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Epilogue", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"],
        "headline-sm": ["Epilogue", "sans-serif"],
        "display-mobile": ["Epilogue", "sans-serif"]
      },
      fontSize: {
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }]
      },

      colors: {
        brand: '#1F3864',
        brandHover: '#15294D',
        surface: '#FFFFFF',
        background: '#F7F8FA',
        border: '#E4E7EC',
        compliantBg: '#DCFCE7',
        compliantText: '#15803D',
        needsReviewBg: '#FEF3C7',
        needsReviewText: '#B45309',
        nonCompliantBg: '#FEE2E2',
        nonCompliantText: '#B91C1C',
        textPrimary: '#1A1D29',
        textSecondary: '#5C6072'
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      keyframes: {
        scan: {
          '0%, 100%': { top: '0%' },
          '50%': { top: '100%' },
        }
      },
      animation: {
        scan: 'scan 2s ease-in-out infinite',
      }
    },
  },
  plugins: [],
}
